services:
  # Backend Development Service
  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: food-detection-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/requirements.txt:/app/requirements.txt
      - ./models:/app/models:ro
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - dev

  # Backend Production Service
  backend-prod:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: food-detection-backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - prod

  # Frontend Development Service (Vite dev server)
  frontend-dev:
    image: node:20-alpine
    container_name: food-detection-frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend-dev
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - dev

  # Frontend Production Service (nginx)
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: food-detection-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-prod
    environment:
      - VITE_API_BASE_URL=/api
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - prod

networks:
  app-network:
    driver: bridge 