services:
  # Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: food-detection-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./models:/app/models:ro
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - food-detection-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: food-detection-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=/api
    restart: unless-stopped
    networks:
      - food-detection-network

networks:
  food-detection-network:
    driver: bridge 