version: '3.8'

services:
  food-detection-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
      - ../models:/app/models:ro
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    # Override the default command to enable hot reloading
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - food-detection-network

networks:
  food-detection-network:
    driver: bridge 