version: '3.8'

services:
  food-detection-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - food-detection-network

networks:
  food-detection-network:
    driver: bridge 